[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.openai.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200